#!/bin/sh
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
export QT_IM_MODULE="xim"
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"
compton &
nm-applet &
python2.7 ~/goagent/local/proxy.py &
exec /usr/bin/awesome
