#!/bin/sh
export XMODIFIERS="@im=ibus"
export XIM=ibus
export XIM_PROGRAM=ibus
export GTK_IM_MODULE="ibus"
export QT_IM_MODULE="xim"
ibus-daemon -d -x -r -n awesome
nm-applet &
conky &
~/goagent/local/proxy.py &
exec /usr/bin/awesome
